owner: tzumowfun
repo: mowfun  # 確認這個是正確的 repo 名稱
user-agent: MowFun

sites:
  - name: MowFun 主網站
    url: https://mowfun.app/
    expectedStatusCodes:
      - 200
      - 301
      - 302
      - 401
    
  - name: Google
    url: https://www.google.com/
    
  - name: GitHub
    url: https://github.com/

status-website:
  baseUrl: /mowfun  # 修改這裡，與您的 repo 名稱一致
  name: MowFun 系統狀態
  introTitle: "服務監控"  
  introMessage: 實時監控系統服務狀態
