owner: mowfun
repo: upptime
user-agent: MowFun

sites:
  - name: MowFun 主網站
    url: https://mowfun.app/
    expectedStatusCodes:
      - 200
      - 301
      - 302
      - 401
      - 403
    maxResponseTime: 30000
    
  - name: Supabase Database
    url: https://wmjleoufkrurqyclafcl.supabase.co/rest/v1/
    
  - name: Supabase Auth
    url: https://wmjleoufkrurqyclafcl.supabase.co/auth/v1/health
    
  - name: Supabase Storage
    url: https://wmjleoufkrurqyclafcl.supabase.co/storage/v1/

status-website:
  name: MowFun 系統狀態
  introTitle: "服務監控"
  introMessage: 實時監控系統服務狀態
