# .upptimerc.yml - 使用系統字體版本
owner: tzumowfun
repo: mowfun

sites:
  - name: mowfun 主頁面
    url: https://mowfun.app
    
  - name: mowfun 登入頁面
    url: https://mowfun.app/login
    
  - name: mowfun 註冊頁面
    url: https://mowfun.app/signup
    
  - name: mowfun 紀錄頁面
    url: https://mowfun.app/log
    
  - name: mowfun 報告頁面
    url: https://mowfun.app/report
    
  - name: Supabase Database
    url: https://wmjleoufkrurqyclafcl.supabase.co/rest/v1/
    expectedStatusCodes:
      - 200
      - 401
    maxResponseTime: 10000
    
  - name: Supabase Auth
    url: https://wmjleoufkrurqyclafcl.supabase.co/auth/v1/settings
    expectedStatusCodes:
      - 200
      - 401
    maxResponseTime: 10000

status-website:
  logoUrl: https://mowfun.app/favicon.ico
  name: Mowfun Status
  introTitle: "Mowfun 服務狀態"
  introMessage: 監控 Mowfun 及相關服務的即時狀態
  baseUrl: /mowfun
  theme: light
  
  # 使用系統字體，避免載入外部字體
  customHeadHtml: |
    <style>
      :root {
        --font-family-body: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', sans-serif;
        --font-family-heading: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', sans-serif;
      }
      body, h1, h2, h3, h4, h5, h6 {
        font-family: var(--font-family-body);
      }
    </style>

schedule: "*/5 * * * *"
assignees:
  - tzumowfun
user-agent: mowfun-uptime-monitor

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *" 
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
