# .upptimerc.yml - 乾淨版本
owner: tzumowfun
repo: mowfun

sites:
  - name: Mowfun 主頁面
    url: https://mowfun.app
    
  - name: Mowfun 登入頁面
    url: https://mowfun.app/login
    
  - name: Mowfun 註冊頁面
    url: https://mowfun.app/signup
    
  - name: Mowfun 紀錄頁面
    url: https://mowfun.app/log
    
  - name: Mowfun 報告頁面
    url: https://mowfun.app/report
    
  - name: Supabase Database
    url: https://wmjleoufkrurqyclafcl.supabase.co/rest/v1/
    expectedStatusCodes:
      - 200
      - 401
    maxResponseTime: 10000
    
  - name: Supabase Auth
    url: https://wmjleoufkrurqyclafcl.supabase.co/auth/v1/settings
    expectedStatusCodes:
      - 200
      - 401
    maxResponseTime: 10000

status-website:
  name: Mowfun Status
  introTitle: "Mowfun 服務狀態監控"
  introMessage: "即時監控 Mowfun 網站及相關服務的運行狀態"
  baseUrl: /mowfun
  theme: light
  
  navbar:
    - title: 回到 mowfun
      href: https://mowfun.app

schedule: "*/5 * * * *"
assignees:
  - tzumowfun
user-agent: mowfun-uptime-monitor
