# .upptimerc.yml - 最佳監控設定

# GitHub repository 設定 (必要!)
owner: your-github-username  # 替換成你的 GitHub 用戶名
repo: your-uptime-repo       # 替換成你的 uptime repository 名稱

# 網站監控設定
sites:
  # 前端頁面 - 正確網址
  - name: mowfun 主頁面
    url: https://mowfun.app
    
  - name: mowfun 登入頁面
    url: https://mowfun.app/login
    
  - name: mowfun 註冊頁面
    url: https://mowfun.app/signup
    
  - name: mowfun 紀錄頁面
    url: https://mowfun.app/log
    
  - name: mowfun 報告頁面
    url: https://mowfun.app/report

  # Supabase 服務監控 - 優化設定
  - name: Supabase Database
    url: https://wmjleoufkrurqyclafcl.supabase.co/rest/v1/
    # 方法1: 接受401為正常狀態（推薦）
    expectedStatusCodes:
      - 200
      - 401
    # 設定合理的超時時間
    maxResponseTime: 10000
    
  - name: Supabase Auth
    url: https://wmjleoufkrurqyclafcl.supabase.co/auth/v1/settings
    # 方法1: 接受401為正常狀態（推薦）
    expectedStatusCodes:
      - 200
      - 401
    # 設定合理的超時時間
    maxResponseTime: 10000

  # 額外監控 Storage（如果需要的話）
  # - name: Supabase Storage
  #   url: https://wmjleoufkrurqyclafcl.storage.supabase.co/storage/v1/s3
  #   expectedStatusCodes:
  #     - 200
  #     - 401
  #     - 403
  #   maxResponseTime: 10000

# 全域設定
status-website:
  # 你的狀態頁面設定 - 修正 GitHub Pages 路徑
  # 移除 cname，讓它使用預設的 GitHub Pages 設定
  # cname: tzumowfun.github.io/mowfun # 註解掉這行
  logoUrl: https://mowfun.app/favicon.ico
  name: Mowfun Status
  introTitle: "Mowfun 服務狀態"
  introMessage: 監控 Mowfun 及相關服務的即時狀態
  # 加入正確的 base path 設定
  baseUrl: /mowfun
  
# 監控頻率設定（重要！）
schedule: "*/5 * * * *"  # 每5分鐘檢查一次，避免觸發 rate limit

# 通知設定
notifications:
  # 可以加入 Slack、Discord、Email 通知
  # - type: slack
  #   webhook: $SLACK_WEBHOOK_URL
  
# 其他重要設定
assignees:
  - tzumowfun

user-agent: mowfun-uptime-monitor

# 設定工作流程權限
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *" 
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
