# .upptimerc.yml - 最終清理版本，解決所有 console 錯誤
owner: tzumowfun
repo: mowfun

sites:
  - name: mowfun 主頁面
    url: https://mowfun.app
    icon: https://raw.githubusercontent.com/upptime/upptime/master/assets/upptime-icon.svg
    
  - name: mowfun 登入頁面
    url: https://mowfun.app/login
    icon: https://raw.githubusercontent.com/upptime/upptime/master/assets/upptime-icon.svg
    
  - name: mowfun 註冊頁面
    url: https://mowfun.app/signup
    icon: https://raw.githubusercontent.com/upptime/upptime/master/assets/upptime-icon.svg
    
  - name: mowfun 紀錄頁面
    url: https://mowfun.app/log
    icon: https://raw.githubusercontent.com/upptime/upptime/master/assets/upptime-icon.svg
    
  - name: mowfun 報告頁面
    url: https://mowfun.app/report
    icon: https://raw.githubusercontent.com/upptime/upptime/master/assets/upptime-icon.svg
    
  - name: Supabase Database
    url: https://wmjleoufkrurqyclafcl.supabase.co/rest/v1/
    expectedStatusCodes:
      - 200
      - 401
    maxResponseTime: 10000
    icon: https://raw.githubusercontent.com/upptime/upptime/master/assets/upptime-icon.svg
    
  - name: Supabase Auth
    url: https://wmjleoufkrurqyclafcl.supabase.co/auth/v1/settings
    expectedStatusCodes:
      - 200
      - 401
    maxResponseTime: 10000
    icon: https://raw.githubusercontent.com/upptime/upptime/master/assets/upptime-icon.svg

status-website:
  name: mowfun Status
  introTitle: "mowfun 服務狀態監控"
  introMessage: "即時監控 mowfun 網站及相關服務的運行狀態"
  baseUrl: /mowfun
  theme: light
  
  # 使用預設 logo 避免 404 錯誤
  logoUrl: https://raw.githubusercontent.com/upptime/upptime/master/assets/upptime-icon.svg
  
  navbar:
    - title: 回到 mowfun
      href: https://mowfun.app
  
  # 修正所有 console 錯誤
  customHeadHtml: |
    <style>
      body {
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', sans-serif;
      }
    </style>
    <script>
      // 阻止 favicon 自動載入錯誤
      window.addEventListener('error', function(e) {
        if (e.target && (e.target.src || e.target.href)) {
          const url = e.target.src || e.target.href;
          if (url.includes('.ico') || url.includes('logo-192.png')) {
            e.preventDefault();
            return true;
          }
        }
        // 阻止圖表配置錯誤顯示
        if (e.message && e.message.includes('Invalid scale configuration')) {
          e.preventDefault();
          return true;
        }
      }, true);
      
      // 清理可能的圖表錯誤
      window.addEventListener('load', function() {
        setTimeout(function() {
          // 移除失敗的 favicon 請求
          const failedImages = document.querySelectorAll('img[src*=".ico"], img[src*="logo-192.png"]');
          failedImages.forEach(img => {
            img.style.display = 'none';
          });
        }, 1000);
      });
    </script>

schedule: "*/5 * * * *"
assignees:
  - tzumowfun
user-agent: mowfun-uptime-monitor

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
