# .upptimerc.yml - 完整正確版本
owner: tzumowfun
repo: mowfun

# 網站監控設定
sites:
  - name: Mowfun 主頁面
    url: https://mowfun.app
    
  - name: Mowfun 登入頁面
    url: https://mowfun.app/login
    
  - name: Mowfun 註冊頁面
    url: https://mowfun.app/signup
    
  - name: Mowfun 紀錄頁面
    url: https://mowfun.app/log
    
  - name: Mowfun 報告頁面
    url: https://mowfun.app/report
    
  - name: Supabase Database
    url: https://wmjleoufkrurqyclafcl.supabase.co/rest/v1/
    expectedStatusCodes:
      - 200
      - 401
    maxResponseTime: 10000
    
  - name: Supabase Auth
    url: https://wmjleoufkrurqyclafcl.supabase.co/auth/v1/settings
    expectedStatusCodes:
      - 200
      - 401
    maxResponseTime: 10000

# 狀態網站設定
status-website:
  name: Mowfun Status
  logoUrl: https://mowfun.app/favicon.ico
  introTitle: "Mowfun 服務狀態監控"
  introMessage: "即時監控 Mowfun 網站及相關服務的運行狀態"
  
  # GitHub Pages 路徑設定 - 這是關鍵！
  baseUrl: /mowfun
  
  # 主題設定
  theme: light
  
  # 導航連結
  navbar:
    - title: 回到 Mowfun
      href: https://mowfun.app
  
  # 使用系統字體避免 CSP 問題
  customHeadHtml: |
    <style>
      body {
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', sans-serif;
      }
    </style>

# 監控頻率 - 每5分鐘檢查一次
schedule: "*/5 * * * *"

# 指定維護人員
assignees:
  - tzumowfun

# 用戶代理設定
user-agent: mowfun-uptime-monitor

# 工作流程排程
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# 通知設定（可選）
# notifications:
#   - type: slack
#     webhook: $SLACK_WEBHOOK_URL
